name: tezart
description: Dart library to connect to Tezos clients. Send transactions and interact with smart contracts!
version: 0.0.0
author: moneytrack.io
homepage: https://github.com/moneytrackio/tezart
repository: https://github.com/moneytrackio/tezart
issue_tracker: https://github.com/moneytrackio/tezart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bs58check: ^1.0.1 # implementation of base58check
  bip39: ^1.0.3 # Mnemonic code for generating deterministic keys
  blake2b: # library used for hash computation
    git: # use pub get version when https://github.com/riclava/blake2b/pull/2 is merged
      url: git://github.com/moneytrackio/blake2b
  convert: ^2.1.1 # Encoders and decoders for converting between different data representations
  dio: ^3.0.10 # http client
  http: ^0.12.2 # TODO: decide whether to use http or dio

dev_dependencies:
  flutter_test: # TODO: Do we need flutter_test ?
    sdk: flutter
  pedantic: ^1.0.0 # linter
  build_runner: ^1.10.0
  mockito: ^4.1.1 # mocks
  #coverage: ^0.13.3
