name: tezart
description: Dart library to connect to Tezos clients. Send transactions and interact with smart contracts!
version: 0.0.0
author: moneytrack.io
homepage: https://github.com/moneytrackio/tezart
repository: https://github.com/moneytrackio/tezart
issue_tracker: https://github.com/moneytrackio/tezart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.4
  bs58check: ^1.0.1
  bip39: ^1.0.3
  unorm_dart: ^0.1.2
  blake2b: # library used for hash computation
    git: # use pub dev version when https://github.com/riclava/blake2b/pull/2 is merged
      url: git://github.com/moneytrackio/blake2b
  password_hash: ^2.0.0
  convert: ^2.1.1
  dio: ^3.0.10
  mockito: ^4.1.1
  http: ^0.12.2

dev_dependencies:
  flutter_test: # TODO: Do we need flutter_test ?
    sdk: flutter
  pedantic: ^1.0.0 # linter
  build_runner: ^1.10.0
  #coverage: ^0.13.3
