name: tezart
description: A Dart library to connect to Tezos clients. Send transactions and interact with smart contracts!
version: 0.0.1-pre
author: moneytrack.io
homepage: https://moneytrackio.github.io/tezart/
repository: https://github.com/moneytrackio/tezart
issue_tracker: https://github.com/moneytrackio/tezart/issues
publish_to: none # prevent publishing : To be remove when the package is ready to be open source and available on pub.dev

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  bs58check: ^1.0.1 # implementation of base58check
  bip39: ^1.0.4 # Mnemonic code for generating deterministic keys
  pointycastle: ^2.0.1 # a library that implements popular crypto algorithms
  convert: ^2.1.1 # Encoders and decoders for converting between different data representations
  dio: ^3.0.10 # http client
  http: ^0.12.2 # TODO: decide whether to use http or dio
  envify: ^2.0.0 # .env files management
  equatable: ^1.2.5
  pinenacl: 0.1.5 # Dart implementation of TweetNacl
  json_serializable: ^3.5.1 # code generation for toJson and fromJson methods
  retry: ^3.0.1 # retry a function if an error happens
  memoize: ^2.0.0 # memoize method calls
  logging: ^0.11.4 # official dart team : Provides APIs for debugging and error logging.
  ansicolor: ^1.0.2 # Use AnsiPen to add ANSI color codes to your log messages.

dev_dependencies:
  pedantic: ^1.9.0 # linter
  build_runner: ^1.10.0
  mockito: ^4.1.1 # mocks
  test: ^1.9.0
  envify_generator: ^1.1.0 # code generation for envify
  test_coverage: ^0.5.0
