name: Run tests
on: pull_request
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest

    services:
      flextesa:
        image: othmanemtk/flextesa-delphibox:1.0.0
        ports:
        - 20000:20000
        options: >-
          --health-cmd "curl -f localhost:20000/chains/main/mempool/pending_operations || exit 1"
          --health-interval 2s
          --health-timeout 60s

    steps:
    - run: curl localhost:20000/chains/main/mempool/pending_operations
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    - run: flutter test

