name: Run tests
on: pull_request
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest

    services:
      flextesa:
        image: othmanemtk/flextesa-delphibox:1.0.0
        ports:
        - 20000:20000
        options: >-
          --health-cmd "curl -f localhost:20000/chains/main/mempool/pending_operations || exit 1"
          --health-interval 2s
          --health-timeout 60s

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - name: Flutter actions
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - name: Flutter pub get
      run: flutter pub get
    - name: Flutter tests
      env:
        TEZOS_NODE_HOST: localhost
        TEZOS_NODE_PORT: ${{ job.services.flextesa.ports[20000] }}
      run: flutter test