name: Run tests

on:
  # Trigger the workflow on push or pull request
  push:
    branches:
      - main
      - v1
  pull_request:

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [2.14.3]

    services:
      flextesa:
        image: othmanemtk/flextesa-delphibox:1.0.2
        ports:
        - 20000:20000
        options: >-
          -e block_time=2
          --health-cmd "curl -f localhost:20000/chains/main/mempool/pending_operations || exit 1"
          --health-interval 2s
          --health-timeout 60s

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - uses: dart-lang/setup-dart@v1.0
      with:
        sdk: ${{ matrix.sdk }}

    - name: Dart pub get
      run: dart pub get

    - name: Documentation generation check
      run: |
        pub global activate dartdoc
        $HOME/.pub-cache/bin/dartdoc

    - name: Dart tests
      run: |
        cp .github/workflows/.env.ci .env.test
        ./tezart coverage

    - name: Collect the code coverage
      uses: codecov/codecov-action@v1.2.1
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./coverage/lcov.info

    - name: Analyse the package with pana
      run: |
        ./tezart pana